### PR TITLE
DD update location

### PR DESCRIPTION
**Pull request by rpassas**
Minor tweak: changing identifier[NPI] to identifier:NPI in the narrative content to match formatting of other slices

### CODE REVIEW

**Review by ptran265 — COMMENTED** [review]
I don't think this was introduced by you, but I'm noticing that the LocationBFDR items in the datadictionary are showing up under 'Coded Content- Demographics' section

**Comment by ptran265** [comment]
looks like the natality data dictionary also has locationbfdr in the coded content section?

this is also a nitpicky type thing but could you move locationBFDR alphabetically? like it should go after EncounterMaternity stuff and before Observation stuff. Everything's alphabetized by profile name except for the EmergingIssues stuff that we stuck at the end

**Comment by rpassas** [comment]
> looks like the natality data dictionary also has locationbfdr in the coded content section?
> 
> this is also a nitpicky type thing but could you move locationBFDR alphabetically? like it should go after EncounterMaternity stuff and before Observation stuff. Everything's alphabetized by profile name except for the EmergingIssues stuff that we stuck at the end

Previous commit moved the locationBFDR out of coded content - I'll make the alphabetizing change

**Comment by ptran265** [comment]
also I'm noticing in some spots, the extension is called patient-birthplace while other times its just 'birthplace'. They seem to link to slightly different places, not sure which is correct?

(see PatientDecedentFetus for example)

**Comment by ptran265** [comment]
image

I think these need to be distinguished using 'type'

**Comment by saulakravitz** [comment]
> image
> 
> I think these need to be distinguished using 'type'

Yes, type = birth, transfer-from, transfer-to, for the three rows.

**Comment by rpassas** [comment]
Added note: type:BFDR = "..." for the name field

**Comment by rpassas** [comment]
> also I'm noticing in some spots, the extension is called patient-birthplace while other times its just 'birthplace'. They seem to link to slightly different places, not sure which is correct?
> 
> (see PatientDecedentFetus for example)

the fsh uses `birthplace` so I am using that and updated the link to go to the official url for the extension

**Review by ptran265 — APPROVED** [review]

**Pull request merged**
