### PR TITLE
Data dict widths and broken links

### PR DESCRIPTION
**Pull request by ptran265**
- adjusted widths of columns in data dictionary
- removed the last column of data dictionary (provider, jurisdiction use) and changed coloring of IJE Name field with some explanation text. Purple text indicates item is unique to Jurisdiction report only. There were no items that were unique to Provider report only. 
- I pulled out the script for generating the data dictionary from the sandbox into this IG, with a note at the top of the script that the user should download the most recent version of the spreadsheets from the sandbox before running the script (later we may consider keeping master copies of spreadsheets in VRCL instead of sandbox). I also trimmed down the script so it only generates the BFDR data dictionaries (sandbox version also generates for VRDR). In the future, perhaps we can include some code to automatically download the spreadsheets. My attempt at doing this was getting an SSL error... so it's commented out for now.

### CODE REVIEW

**Comment by saulakravitz** [comment]
Looks good to me, but I defer to Robert's judgement.

**Review by saulakravitz — COMMENTED** [review]
Robert should review the script....content looks good to me.

**Comment by ptran265** [comment]
Thanks, but I realized I should change the notes ("See StateLiterals" for example) to reference VRCL, instead of changing the usage.html in BFDR.. waiting for it to finish building

**Review by saulakravitz — APPROVED** [review]
Looks good...Let Robert review the script.

**Pull request merged**
